# Gunakan base image Python
FROM python:3.9-slim

# Set environment variables
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV && $VIRTUAL_ENV/bin/pip install --upgrade pip
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Set working directory
WORKDIR /app

# Salin file proyek ke container
COPY . .

# Instal dependensi
RUN pip install -r requirements.txt

# Perintah untuk menjalankan aplikasi
CMD ["python", "sources/add2vals.py"]
